blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from webapp.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', ArticleListView.as_view(), name='index'),
    path('article/<int:pk>', ArticleDetailView.as_view(), name='article_view'),
    path('article/create', ArticleCreateView.as_view(), name='article_create'),
    path('article/<int:pk>/update', ArticleUpdateView.as_view(), name='article_update'),
    path('article/<int:pk>/delete', ArticleDeleteView.as_view(), name='article_delete'),
    path('user', UserListView.as_view(), name='users_list'),
    path('user/<int:pk>', UserDetailView.as_view(), name='user_view'),
    path('article/<int:pk>/comment/create', CommentCreateView.as_view(), name='comment_create'),
    path('comment/<int:pk>/update', CommentUpdateView.as_view(), name='comment_update'),
    url(r'^search/', SearchView.as_view(), name='search'),

]

webapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=255, null=False, blank=False)
    text = models.TextField(max_length=3000, null=True, blank=True, verbose_name='Текст')
    author = models.ForeignKey(User, on_delete=models.PROTECT, related_name='articles', verbose_name='Автор')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='info', verbose_name='Пользователь')
    favorites = models.ManyToManyField(Article, related_name='favorites', verbose_name='Избранное')

    def __str__(self):
        return self.user.username


class Rate(models.Model):
    RATE_HORRIBLE = 'horrible'
    RATE_BAD = 'bad'
    RATE_NORMAL = 'normal'
    RATE_GOOD = 'good'
    RATE_BEST = 'best'

    RATE_CHOICES = (
        (RATE_HORRIBLE, 'Ужасно'),
        (RATE_BAD, 'Плохо'),
        (RATE_NORMAL, 'Нормально'),
        (RATE_GOOD, 'Хорошо'),
        (RATE_BEST, 'Отлично'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='rates', verbose_name='Пользователь')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='rates', verbose_name='Статья')
    rate = models.CharField(max_length=20, choices=RATE_CHOICES, default=RATE_BEST, verbose_name='Статус')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')

    class Meta:
        unique_together = ('user', 'article',)

    def __str__(self):
        return "%s / %s / %s" % (self.user, self.article, self.get_rate_display())


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments', verbose_name='Пользователь')
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments', verbose_name='Статья')
    parent_id = models.ForeignKey('Comment', null=True, blank=True, related_name='children', on_delete=models.CASCADE, verbose_name='Родительский коммент')
    text = models.TextField(max_length=3000, null=False, blank=False, verbose_name='Текст комментария')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')

    def __str__(self):
        return "(%s) %s | %s" % (self.pk, self.user, self.article)

webapp/forms.py
from django import forms
from webapp.models import *


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'text', 'author']


class CommentFormCreate(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['user', 'parent_id', 'text']


class CommentFormUpdate(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['parent_id', 'text']

webapp/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from webapp.forms import *
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
# Create your views here.


class ArticleListView(ListView):
    model = Article
    template_name = 'index.html'


class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleForm
    template_name = 'article_create.html'
    success_url = reverse_lazy('index')


class ArticleUpdateView(UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = 'article_update.html'
    success_url = reverse_lazy('index')


class ArticleDeleteView(DeleteView):
    model = Article
    template_name = 'article_delete.html'
    success_url = reverse_lazy('index')


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'article_detail.html'


class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentFormCreate
    template_name = 'comment_create.html'
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        form.instance.article = get_object_or_404(Article, pk=self.kwargs['pk'])
        form.save()
        return super(CommentCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['apk'] = self.kwargs['pk']
        return context


class CommentUpdateView(UpdateView):
    model = Comment
    form_class = CommentFormUpdate
    template_name = 'comment_update.html'
    success_url = reverse_lazy('index')


class UserListView(ListView):
    model = User
    template_name = 'user_list.html'


class UserDetailView(DetailView):
    model = User
    template_name = 'user_detail.html'


class SearchView(ListView):
    model = Article
    template_name = 'search.html'

    def get_queryset(self):
        article_title = self.request.GET.get('article_title')
        self.query_text = article_title
        self.article_lists = Article.objects.filter(title__icontains=article_title) | Article.objects.filter(text__icontains=article_title)
        return self.article_lists

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['article_lists'] = self.article_lists
        context['query_text'] = self.query_text
        return context

webapp/templates/article_create.html
{% extends 'base.html' %}

{% block title %}New Article{% endblock %}

{% block content %}

    <div class="panel panel-primary">
        <div class="panel-heading">New Article</div>
            <div class="panel-body">
                <form action="{% url 'article_create' %}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <label style="display: block" for="{{ field.name }}">{{ field.label }}</label>
                            {{ field }}
                          </div>
                    {% endfor %}
                    <button class="btn btn-primary" type="submit">Save</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

webapp/templates/article_delete.html
{% extends 'base.html' %}

{% block title %}Delete Article{% endblock %}

{% block content %}

    <div class="panel panel-primary">
        <div class="panel-heading">Delete Article</div>
            <div class="panel-body">
                <h4>Are you sure?</h4>
                <form action="{% url 'article_delete' article.pk %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

webapp/templates/article_detail.html
{% extends 'base.html' %}

{% block title %}{{ article.title }}{% endblock %}

{% block content %}

    <div class="panel panel-primary">
        <div class="panel-heading">{{ article.title }}</div>
            <div class="panel-body">
                <p><b>Author:</b> {{ article.author }}</p>
                <p><i>Date: {{ article.created_at }}</i></p>
                <br>
                <br>
                <p>{{ article.text }}</p>

                <div class="line_helper"></div>

                <h3>Rates</h3>
                    {% for rate in article.rates.all %}
                        <span>
                            <b>{{ rate.user }}:</b>
                            {{ rate.get_rate_display }}<br>
                        </span>
                    {% endfor %}

                <div class="line_helper"></div>

                <h3>Comments</h3>

               <p><a class="btn btn-primary" href="{% url 'comment_create' article.pk%}">Add comment</a></p>

                <ul class="comment-list">
                    {% for comment in article.comments.all %}

                        {% if not comment.parent_id.id %}

                            <ul class="comment list-unstyled">
                                {% include "comment.html" %}
                            </ul>

                        {% endif %}
                    {% endfor %}
                </ul>

{#                    <p>{{ comment.text }}</p>#}
{#                    <p>{{ comment.parent_id.id }}</p>#}

            </div>
        </div>
    </div>

{% endblock %}

webapp/templates/article_update.html
{% extends 'base.html' %}

{% block title %}{{ article.title }}{% endblock %}

{% block content %}

    <div class="panel panel-primary">
        <div class="panel-heading">Update Article</div>
            <div class="panel-body">
                <form action="{% url 'article_update' form.instance.pk %}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <label style="display: block" for="{{ field.name }}">{{ field.label }}</label>
                            {{ field }}
                          </div>
                    {% endfor %}
                    <button class="btn btn-primary" type="submit">Save</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Articles{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/">Main</a></li>
                <li><a href="{% url 'users_list' %}">Users</a></li>
                <li><a href="{% url 'article_create' %}">New Article</a></li>


                {% with request.resolver_match.view_name as view_name %}
                    {% if view_name == 'article_view' %}
                        <li><a href="{% url 'comment_create' article.pk%}">Add comment</a></li>
                        <li><a href="{% url 'article_update' article.pk %}">Edit Article</a></li>
                        <li><a href="{% url 'article_delete' article.pk %}">Delete Article</a></li>
                    {% endif %}
                {% endwith %}
                {% block menu %}{% endblock %}
            </ul>


            <div class="nav navbar-right">

                <form class="navbar-form navbar-left" action="{% url 'search' %}" method="get" style="margin-top: 10px">
                    <div class="form-group">
                        <input id="search" name="article_title" type="text" class="form-control"
                               placeholder="Поиск">
                    </div>

                    <button class="searchbutton" type="submit">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>


                </form>

            </div>


        </div>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            {% block content %}{% endblock %}
        </div>
    </div>
</div>

</body>
</html>

webapp/templates/comment.html
<li class="comment">
    <div class="comment_text">
       <b>{{ comment.user }}</b>: {{ comment.created_at }}<br>
        {{ comment.text }}<br/>
        <a href="{% url 'comment_update' comment.pk %}">Edit comment</a>
    </div>

    {% if comment.children  %}
        <ul class="list-unstyled">
            {% for comment in comment.children.all %}
                    {% include 'comment.html' %}
            {% endfor %}
        </ul>
    {% endif %}
</li>

webapp/templates/comment_create.html
{% extends 'base.html' %}

{% block title %}New Comment{% endblock %}

{% block content %}


    <div class="panel panel-primary">
        <div class="panel-heading">New Comment</div>

            <div class="panel-body">
                <form action="{% url 'comment_create'  apk  %}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <label style="display: block" for="{{ field.name }}">{{ field.label }}</label>
                            {{ field }}
                          </div>
                    {% endfor %}
                    <button class="btn btn-primary" type="submit">Save</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

webapp/templates/comment_update.html
{% extends 'base.html' %}

{% block title %}Update Comment{% endblock %}

{% block content %}


    <div class="panel panel-primary">
        <div class="panel-heading">Update Comment</div>

            <div class="panel-body">
                <form action="{% url 'comment_update' form.instance.pk %}" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <label style="display: block" for="{{ field.name }}">{{ field.label }}</label>
                            {{ field }}
                          </div>
                    {% endfor %}
                    <button class="btn btn-primary" type="submit">Save</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

webapp/templates/index.html
{% extends 'base.html' %}

{% block title %}Main{% endblock %}

{% block content %}

    <div class="panel panel-primary">
        <div class="panel-heading">Articles List</div>
            <div class="panel-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Author</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    {% for a in article_list %}
                            <tr>
                                <td>{{ a.title }}</td>
                                <td>{{ a.author }}</td>
                                <td>
                                    <a href="{% url 'article_view' a.pk %}" class="btn btn-primary">View</a>
                                    <a href="{% url 'article_update' a.pk %}" class="btn btn-warning">Edit</a>
                                    <a href="{% url 'article_delete' a.pk %}" class="btn btn-danger">Delete</a>
                                </td>
                            </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>


{% endblock %}

webapp/templates/search.html
{% extends 'base.html' %}

{% block title %}Main{% endblock %}

{% block content %}

    <h1></h1>

    <div class="panel panel-primary">
        <div class="panel-heading">Search result by: <span>{{ query_text }}</span></div>
            <div class="panel-body">
                {% if article_lists %}
                    <ul class="list-unstyled search_list">
                        {% for article in article_lists %}
                            <li>
                                <a href="{% url 'article_view' article.pk %}">{{ article.title }}</a><br/>
                                <div class="date">{{ article.created_at }}</div>
                            </li>
                        {% endfor %}
                    </ul>

                {% else %}
                    <p>Не найдено публикаций по вашему запросу<br>Попробуйте повторить запрос с другой формулировкой</p>
                {% endif %}
            </div>
        </div>
    </div>




{% endblock %}

webapp/templates/user_detail.html
{% extends 'base.html' %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}

    <div class="panel panel-primary">
        <div class="panel-heading">{{ user.username }}</div>
            <div class="panel-body">


                <h3>User Articles</h3>
                <ul>
                    {% for a in user.articles.all %}
                       <li><a href="{% url 'article_view' a.pk %}">{{ a.title }}</a></li>
                    {% endfor %}
                </ul>


                <div class="line_helper"></div>
                <h3>User Favorites</h3>
                <ul>
                    {% for a in user.info.favorites.all %}

                        <li><a href="{% url 'article_view' a.pk %}">{{ a.title }}</a></li>

                    {% endfor %}
                </ul>


            </div>
        </div>
    </div>

{% endblock %}

webapp/templates/user_list.html
{% extends 'base.html' %}

{% block title %}User List{% endblock %}

{% block content %}

    <div class="panel panel-primary">
        <div class="panel-heading">Articles List</div>
            <div class="panel-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    {% for u in user_list %}
                            <tr>
                                <td>{{ u.username }}</td>
                                <td>
                                    <a href="{% url 'user_view' u.pk %}" class="btn btn-primary">View</a>
{#                                    <a href="{% url 'update_employee' e.pk %}" class="btn btn-primary">Edit</a>#}
{#                                    <a href="{% url 'delete_employee' e.pk %}" class="btn btn-danger">Delete</a>#}
                                </td>
                            </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>


{% endblock %}